base: 'https://surfcamp-team2.ddev.site/'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=7'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
rootPageId: 1
routes: {  }
