styles:
  content:
    links:
      keep: path
      extTarget: _blank
    allowTags: 'a, abbr, acronym, address, article, aside, b, bdo, big, blockquote, br, caption, center, cite, code, col, colgroup, dd, del, dfn, dl, div, dt, em, figcaption, figure, font, footer, header, h1, h2, h3, h4, h5, h6, hr, i, img, ins, kbd, label, li, link, meta, nav, ol, p, pre, q, s, samp, sdfield, section, small, span, strike, strong, style, sub, sup, table, thead, tbody, tfoot, td, th, tr, title, tt, u, ul, var'
    textmedia:
      maxW: 600
      maxWInText: 300
      columnSpacing: 10
      borderWidth: 2
      borderPadding: 0
socials:
  channels:
    linkedin:
      link: 'https://www.linkedin.com/company/typo3-association'
    x:
      link: 'https://x.com/typo3'
    github:
      link: 'https://github.com/typo3'
    youtube:
      link: 'https://www.youtube.com/@typo3'
style:
  data:
    buttonBorderRadius:
      value: rounded
  buttonBorderRadius: round
  primaryColor: '#397e6f'
  secondaryColor: '#4dd5ff'
  theme: light
