styles:
  content:
    links:
      keep: path
      extTarget: '_blank'
    allowTags: 'a, abbr, acronym, address, article, aside, b, bdo, big, blockquote, br, caption, center, cite, code, col, colgroup, dd, del, dfn, dl, div, dt, em, figcaption, figure, font, footer, header, h1, h2, h3, h4, h5, h6, hr, i, img, ins, kbd, label, li, link, meta, nav, ol, p, pre, q, s, samp, sdfield, section, small, span, strike, strong, style, sub, sup, table, thead, tbody, tfoot, td, th, tr, title, tt, u, ul, var'
    textmedia:
      maxW: 600
      maxWInText: 300
      columnSpacing: 10
      borderWidth: 2
      borderPadding: 0

socials:
  channels:
    xing:
      link: 'https://www.xing.com/profile/Georg_Ringer'
    linkedin:
      link: 'https://www.linkedin.com/in/georgringer'
    x:
      link: 'https://twitter.com/georg_ringer'
    github:
      link: 'https://github.com/georgringer'

logo:
  path: '/fileadmin/logo/georg-ringer.svg'
