socials:
  facebook:
    link: 'https://www.facebook.com/'
  instagram:
    link: 'https://www.instagram.com/'
  threads:
    link: ''
  whatsapp:
    link: ''
  youtube:
    link: ''
  vimeo:
    link: ''
  xing:
    link: 'https://www.xing.com/'
  linkedin:
    link: ''
  pinterest:
    link: ''
  snapchat:
    link: ''
  tiktok:
    link: ''
  reddit:
    link: 'https://www.reddit.com/'
  x:
    link: ''
  twitch:
    link: ''
  tumblr:
    link: ''
