settings:
  socials.showInFooter:
    label: 'Enable Social Links in Footer'
    description: 'Enable social links in the Header'
    type: bool
    default: true
  socials.showInHeader:
    label: 'Enable Social Links in Header'
    description: 'Enable social links in the Header'
    type: bool
    default: true
  socials.showActionButtons:
    label: 'Enable Social Links as floating action buttons'
    description: 'Enable social links as floating action buttons'
    type: bool
    default: true
  socials.channels.facebook.link:
    label: 'Facebook Link'
    description: 'Link to your Facebook profile'
    type: string
    default: ''
  socials.channels.instagram.link:
    label: 'Instagram Link'
    description: 'Link to your Instagram profile'
    type: string
    default: ''
  socials.channels.threads.link:
    label: 'Threads Link'
    description: 'Link to your Threads profile'
    type: string
    default: ''
  socials.channels.whatsapp.link:
    label: 'Threads Link'
    description: 'Link to your Whatsapp channel'
    type: string
    default: ''
  socials.channels.youtube.link:
    label: 'Youtube Link'
    description: 'Link to your Youtube channel'
    type: string
    default: ''
  socials.channels.vimeo.link:
    label: 'Vimeo Link'
    description: 'Link to your Vimeo channel'
    type: string
    default: ''
  socials.channels.xing.link:
    label: 'XING Link'
    description: 'Link to your XING profile'
    type: string
    default: ''
  socials.channels.linkedin.link:
    label: 'LinkedIn Link'
    description: 'Link to your LinkedIn profile'
    type: string
    default: ''
  socials.channels.snapchat.link:
    label: 'Snapchat Link'
    description: 'Link to your Snapchat profile'
    type: string
    default: ''
  socials.channels.tiktok.link:
    label: 'TikTok Link'
    description: 'Link to your TikTok channel'
    type: string
    default: ''
  socials.channels.reddit.link:
    label: 'Reddit Link'
    description: 'Link to your Reddit profile'
    type: string
    default: ''
  socials.channels.x.link:
    label: 'X/Twitter Link'
    description: 'Link to your X/Twitter profile'
    type: string
    default: ''
  socials.channels.twitch.link:
    label: 'Twitch Link'
    description: 'Link to your Twitch channel'
    type: string
    default: ''
  socials.channels.tumblr.link:
    label: 'Tumblr Link'
    description: 'Link to your Tumblr profile'
    type: string
    default: ''
  socials.channels.pinterest.link:
    label: 'Pinterest Link'
    description: 'Link to your Pinterest profile'
    type: string
    default: ''
