config:
  projects:
    detailPid: 9
    storagePid: 8
socials:
  showInFooter: false
  showInHeader: false
  showActionButtons: true
  channels:
    facebook:
      link: 'https://www.facebook.com/'
    instagram:
      link: 'https://www.instagram.com/'
    threads:
      link: ''
    whatsapp:
      link: ''
    youtube:
      link: ''
    vimeo:
      link: ''
    xing:
      link: 'https://www.xing.com/'
    linkedin:
      link: ''
    pinterest:
      link: ''
    snapchat:
      link: ''
    tiktok:
      link: ''
    reddit:
      link: 'https://www.reddit.com/'
    x:
      link: ''
    twitch:
      link: ''
    tumblr:
      link: ''
style:
  variables:
    primaryColor:
      key: 'color-primary'
      value: '#000000'
    secondaryColor:
      key: 'color-secondary'
      value: '#000000'
  data:
    theme:
      key: 'theme'
      value: 'dark'
    buttonBorderRadius:
      key: 'button-border-radius'
      value: 'none'
